### ISSUE TITLE
error handling / passing in options

### ISSUE THREAD

**Issue by RnbWd** [vitaly-t/gulp-decomment#1]
I'm not sure when I'll have a chance to submit a pull request - but the section commented out (just fyi) is checking to see if the user passed in an options object eg. `{trim: true, safe: true}`. And then it turns the option on/off as specified (or errors if they did something weird)

**Comment by vitaly-t** [comment]
@RnbWd I have finished this library and released it:
- Changed the test platform and rewritten the tests;
- Added code coverage, brought it to 100%
- Added integration for Travis + Coveralls
- Refactored the implementation quite a bit
- Updated the documentation a lot.

Thank you for your help in getting started!!! :+1:
